-- ============================================================
-- V1__baseline.sql  (ET.TEE fashion backend)
-- Generated from the live schema via JDBC introspection.
-- Ignored on databases already baselined; used to build fresh ones.
-- ============================================================

-- ------------------------------------------------------------
-- Sequences backing serial columns
-- ------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS banners_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS campaign_analytics_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS campaigns_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS product_placements_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS user_behavior_events_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS voucher_redemptions_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS vouchers_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;


-- ---------- activity_logs ----------
CREATE TABLE IF NOT EXISTS activity_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    ip_address character varying(255),
    target_entity character varying(255),
    target_id character varying(255),
    user_id character varying(255),
    CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);

-- ---------- ai_model_versions ----------
CREATE TABLE IF NOT EXISTS ai_model_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    model_name character varying(255) NOT NULL,
    version_string character varying(255) NOT NULL,
    CONSTRAINT ai_model_versions_pkey PRIMARY KEY (id)
);

-- ---------- banners ----------
CREATE TABLE IF NOT EXISTS banners (
    id bigint DEFAULT nextval('banners_id_seq'::regclass) NOT NULL,
    title character varying(255) NOT NULL,
    subtitle character varying(255),
    image_url character varying(255) NOT NULL,
    link_url character varying(255),
    position character varying(255) DEFAULT 'HERO'::character varying NOT NULL,
    display_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_by character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    priority integer DEFAULT 0,
    status character varying(255) DEFAULT 'ACTIVE'::character varying,
    updated_by character varying(255),
    CONSTRAINT banners_pkey PRIMARY KEY (id)
);

-- ---------- campaign_analytics ----------
CREATE TABLE IF NOT EXISTS campaign_analytics (
    id bigint DEFAULT nextval('campaign_analytics_id_seq'::regclass) NOT NULL,
    campaign_id bigint,
    event_type character varying(255) NOT NULL,
    product_id character varying(255),
    banner_id bigint,
    voucher_id bigint,
    guest_token character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    session_id character varying(255),
    user_id character varying(255),
    order_id bigint,
    revenue numeric(38,2) DEFAULT 0,
    CONSTRAINT campaign_analytics_pkey PRIMARY KEY (id)
);

-- ---------- campaigns ----------
CREATE TABLE IF NOT EXISTS campaigns (
    id bigint DEFAULT nextval('campaigns_id_seq'::regclass) NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    banner_ids bigint[],
    voucher_ids bigint[],
    is_active boolean DEFAULT true,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_by character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    code character varying(255),
    goal character varying(255) DEFAULT 'SALES'::character varying,
    status character varying(255) DEFAULT 'DRAFT'::character varying,
    budget numeric(38,2) DEFAULT 0,
    updated_by character varying(255),
    CONSTRAINT campaigns_pkey PRIMARY KEY (id),
    CONSTRAINT uq_campaigns_code UNIQUE (code)
);

-- ---------- cart_items ----------
CREATE TABLE IF NOT EXISTS cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    quantity integer NOT NULL,
    updated_at timestamp(6) without time zone,
    cart_id bigint NOT NULL,
    product_variant_id bigint NOT NULL,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

-- ---------- carts ----------
CREATE TABLE IF NOT EXISTS carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id character varying(255),
    guest_token character varying(255),
    CONSTRAINT carts_pkey PRIMARY KEY (id),
    CONSTRAINT uk4g6bj0ig78lgdbyxguevthpn9 UNIQUE (guest_token),
    CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id)
);

-- ---------- categories ----------
CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(500),
    name character varying(100) NOT NULL,
    slug character varying(150),
    image_url character varying(500),
    parent_id bigint,
    active boolean DEFAULT true,
    display_order integer DEFAULT 0,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT uk_cat_name_parent UNIQUE (name, parent_id),
    CONSTRAINT uk_cat_slug UNIQUE (slug),
    CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug),
    CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name)
);

-- ---------- cod_reconciliation_items ----------
CREATE TABLE IF NOT EXISTS cod_reconciliation_items (
    item_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cod_amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reconciliation_id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    CONSTRAINT cod_reconciliation_items_pkey PRIMARY KEY (item_id),
    CONSTRAINT uk2wjj51nrif4qopbmok7f4yp03 UNIQUE (shipment_id)
);

-- ---------- cod_reconciliations ----------
CREATE TABLE IF NOT EXISTS cod_reconciliations (
    reconciliation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    item_count integer NOT NULL,
    note character varying(500),
    reconciled_at timestamp(6) without time zone NOT NULL,
    reconciled_by character varying(100) NOT NULL,
    reconciled_by_name character varying(150),
    reconciliation_code character varying(50) NOT NULL,
    shop_id bigint,
    status character varying(30) NOT NULL,
    total_cod_amount numeric(15,2) NOT NULL,
    CONSTRAINT cod_reconciliations_pkey PRIMARY KEY (reconciliation_id),
    CONSTRAINT ukgrwhufe6atxxvr18uqsauu7fl UNIQUE (reconciliation_code)
);

-- ---------- cskh_voucher_grants ----------
CREATE TABLE IF NOT EXISTS cskh_voucher_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    customer_id character varying(255) NOT NULL,
    period character varying(7) NOT NULL,
    reason character varying(500),
    shop_id bigint,
    staff_id character varying(255) NOT NULL,
    ticket_id character varying(255) NOT NULL,
    voucher_code character varying(255) NOT NULL,
    voucher_id bigint NOT NULL,
    CONSTRAINT cskh_voucher_grants_pkey PRIMARY KEY (id)
);

-- ---------- cskh_voucher_quotas ----------
CREATE TABLE IF NOT EXISTS cskh_voucher_quotas (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    period character varying(7) NOT NULL,
    quota_amount numeric(38,2) NOT NULL,
    shop_id bigint,
    staff_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    used_amount numeric(38,2) NOT NULL,
    CONSTRAINT cskh_voucher_quotas_pkey PRIMARY KEY (id),
    CONSTRAINT ukl7rv7eymf944yevrehnypi13g UNIQUE (staff_id, period)
);

-- ---------- email_logs ----------
CREATE TABLE IF NOT EXISTS email_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    error_message text,
    recipient character varying(255) NOT NULL,
    status character varying(255),
    subject character varying(255),
    CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);

-- ---------- email_verification_codes ----------
CREATE TABLE IF NOT EXISTS email_verification_codes (
    id character varying(255) NOT NULL,
    attempt_count integer NOT NULL,
    code_hash character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    max_attempts integer NOT NULL,
    status character varying(255) NOT NULL,
    used_at timestamp(6) without time zone,
    user_id character varying(255) NOT NULL,
    CONSTRAINT email_verification_codes_pkey PRIMARY KEY (id)
);

-- ---------- feature_flags ----------
CREATE TABLE IF NOT EXISTS feature_flags (
    flag_key character varying(100) NOT NULL,
    description character varying(255),
    is_enabled boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT feature_flags_pkey PRIMARY KEY (flag_key)
);

-- ---------- inventories ----------
CREATE TABLE IF NOT EXISTS inventories (
    inventory_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id bigint NOT NULL,
    product_name character varying(200) NOT NULL,
    quantity_on_hand integer NOT NULL,
    quantity_reserved integer NOT NULL,
    reorder_level integer NOT NULL,
    warehouse_location character varying(100),
    shop_id bigint,
    CONSTRAINT inventories_pkey PRIMARY KEY (inventory_id),
    CONSTRAINT uk3bms153u88bt0daekfy4qpj6k UNIQUE (product_id)
);

-- ---------- inventory_adjustments ----------
CREATE TABLE IF NOT EXISTS inventory_adjustments (
    adjustment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    approved_by bigint,
    created_at timestamp(6) without time zone NOT NULL,
    difference integer NOT NULL,
    reason character varying(500) NOT NULL,
    requested_by bigint,
    status character varying(30) NOT NULL,
    inventory_id bigint NOT NULL,
    CONSTRAINT inventory_adjustments_pkey PRIMARY KEY (adjustment_id)
);

-- ---------- login_attempts ----------
CREATE TABLE IF NOT EXISTS login_attempts (
    id character varying(255) NOT NULL,
    attempted_at timestamp(6) without time zone,
    email character varying(255),
    ip_address character varying(255),
    success boolean,
    CONSTRAINT login_attempts_pkey PRIMARY KEY (id)
);

-- ---------- manufacturers ----------
CREATE TABLE IF NOT EXISTS manufacturers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contact_email character varying(150),
    country character varying(100),
    created_at timestamp(6) without time zone,
    description text,
    name character varying(255) NOT NULL,
    product_count integer,
    updated_at timestamp(6) without time zone,
    website character varying(255),
    CONSTRAINT manufacturers_pkey PRIMARY KEY (id)
);

-- ---------- order_items ----------
CREATE TABLE IF NOT EXISTS order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color character varying(255),
    price numeric(38,2),
    quantity integer,
    reviewed boolean NOT NULL,
    size character varying(255),
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    color_snapshot character varying(255),
    image_snapshot character varying(255),
    sale_price double precision,
    size_snapshot character varying(255),
    product_name_snapshot character varying(255) DEFAULT 'Sản phẩm'::character varying NOT NULL,
    unit_price double precision DEFAULT 0 NOT NULL,
    total_price double precision DEFAULT 0 NOT NULL,
    variant_id bigint DEFAULT 0 NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

-- ---------- order_lookup_audit_logs ----------
CREATE TABLE IF NOT EXISTS order_lookup_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id character varying(255) NOT NULL,
    actor_name character varying(255),
    actor_role character varying(255),
    actor_shop_id bigint,
    created_at timestamp(6) without time zone,
    found_order_code character varying(255),
    found_order_id bigint,
    search_query character varying(255) NOT NULL,
    search_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT order_lookup_audit_logs_pkey PRIMARY KEY (id)
);

-- ---------- order_notes ----------
CREATE TABLE IF NOT EXISTS order_notes (
    note_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    order_id bigint NOT NULL,
    CONSTRAINT order_notes_pkey PRIMARY KEY (note_id)
);

-- ---------- order_status_history ----------
CREATE TABLE IF NOT EXISTS order_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    changed_by character varying(255),
    created_at timestamp(6) without time zone,
    new_status character varying(255) NOT NULL,
    note text,
    old_status character varying(255),
    order_id bigint NOT NULL,
    from_status character varying(255),
    reason text,
    status character varying(255),
    CONSTRAINT order_status_history_pkey PRIMARY KEY (id)
);

-- ---------- orders ----------
CREATE TABLE IF NOT EXISTS orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id character varying(255),
    customer_email character varying(255),
    note text,
    guest_token character varying(255),
    order_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cancel_reason character varying(500),
    phone character varying(30),
    shipping_address character varying(500),
    sla_deadline timestamp(6) without time zone,
    customer_name character varying(255),
    customer_phone character varying(255),
    shipping_address_snapshot text,
    payment_method character varying(255),
    payment_status character varying(255),
    order_status character varying(255),
    shipping_fee double precision DEFAULT 0,
    subtotal double precision DEFAULT 0,
    discount_total double precision DEFAULT 0,
    total_amount double precision DEFAULT 0,
    order_code character varying(255),
    voucher_code character varying(255),
    voucher_id bigint,
    shop_id bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_code_key UNIQUE (order_code)
);

-- ---------- password_reset_tokens ----------
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id character varying(255) NOT NULL,
    attempt_count integer NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    locked_at timestamp(6) without time zone,
    max_attempts integer NOT NULL,
    otp_hash character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    used_at timestamp(6) without time zone,
    user_id character varying(255) NOT NULL,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id)
);

-- ---------- product_images ----------
CREATE TABLE IF NOT EXISTS product_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alt character varying(255),
    image_url character varying(1000) NOT NULL,
    is_primary boolean,
    sort_order integer,
    product_id bigint NOT NULL,
    color_code character varying(30),
    color_hex character varying(50),
    CONSTRAINT product_images_pkey PRIMARY KEY (id)
);

-- ---------- product_placements ----------
CREATE TABLE IF NOT EXISTS product_placements (
    id bigint DEFAULT nextval('product_placements_id_seq'::regclass) NOT NULL,
    placement_key character varying(60) NOT NULL,
    product_id bigint NOT NULL,
    position integer DEFAULT 0 NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_placements_pkey PRIMARY KEY (id)
);

-- ---------- product_recommendation_tags ----------
CREATE TABLE IF NOT EXISTS product_recommendation_tags (
    product_id bigint NOT NULL,
    tag character varying(255)
);

-- ---------- product_reviews ----------
CREATE TABLE IF NOT EXISTS product_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    is_verified_purchase boolean NOT NULL,
    purchased_color character varying(255),
    purchased_size character varying(255),
    rating integer NOT NULL,
    updated_at timestamp(6) without time zone,
    product_id bigint NOT NULL,
    user_id character varying(255),
    customer_name_snapshot character varying(255),
    deleted_at timestamp(6) without time zone,
    order_item_id bigint,
    status character varying(255) DEFAULT 'APPROVED'::character varying NOT NULL,
    verified_purchase boolean DEFAULT true NOT NULL,
    CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
    CONSTRAINT product_reviews_order_item_id_key UNIQUE (order_item_id)
);

-- ---------- product_style_tags ----------
CREATE TABLE IF NOT EXISTS product_style_tags (
    product_id bigint NOT NULL,
    tag character varying(255)
);

-- ---------- product_variants ----------
CREATE TABLE IF NOT EXISTS product_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color character varying(50),
    price numeric(12,2),
    size character varying(50),
    sku character varying(100) NOT NULL,
    stock integer NOT NULL,
    product_id bigint NOT NULL,
    available_quantity integer NOT NULL,
    color_hex character varying(50),
    sale_price numeric(12,2),
    color_code character varying(30),
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT ukq935p2d1pbjm39n0063ghnfgn UNIQUE (sku)
);

-- ---------- products ----------
CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    gender character varying(20),
    material character varying(100),
    name character varying(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    style character varying(100),
    updated_at timestamp(6) without time zone,
    category_id bigint,
    is_best_seller boolean,
    is_new boolean,
    is_sale boolean,
    product_type character varying(100),
    sale_price numeric(12,2),
    slug character varying(255) NOT NULL,
    status character varying(50),
    target_group character varying(50),
    average_rating double precision,
    sold_count integer,
    total_reviews integer,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT ukostq1ec3toafnjok09y9l7dox UNIQUE (slug)
);

-- ---------- proof_of_delivery ----------
CREATE TABLE IF NOT EXISTS proof_of_delivery (
    proof_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivered_at timestamp(6) without time zone NOT NULL,
    image_url character varying(1000),
    note character varying(1000),
    receiver_name character varying(150) NOT NULL,
    shipment_id bigint NOT NULL,
    CONSTRAINT proof_of_delivery_pkey PRIMARY KEY (proof_id),
    CONSTRAINT uke88ekl8a1htjvhe0bs9tdjgkn UNIQUE (shipment_id)
);

-- ---------- role_permissions ----------
CREATE TABLE IF NOT EXISTS role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission character varying(100) NOT NULL,
    role_code character varying(50) NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT uk_role_permission UNIQUE (role_code, permission)
);

-- ---------- roles ----------
CREATE TABLE IF NOT EXISTS roles (
    code character varying(50) NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (code)
);

-- ---------- shipments ----------
CREATE TABLE IF NOT EXISTS shipments (
    shipment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    carrier_name character varying(150) NOT NULL,
    cod_amount numeric(15,2),
    cod_reconciled boolean NOT NULL,
    delivered_at timestamp(6) without time zone,
    handover_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    tracking_code character varying(100) NOT NULL,
    order_id bigint NOT NULL,
    delivery_proof_url character varying(1000),
    CONSTRAINT shipments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'HANDED_OVER'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'EXCEPTION'::character varying, 'RETURNED'::character varying, 'pending'::character varying, 'handed_over'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'exception'::character varying, 'returned'::character varying])::text[]))),
    CONSTRAINT shipments_pkey PRIMARY KEY (shipment_id),
    CONSTRAINT uk3welgwg6vbaaqfqdrp2f4ynwc UNIQUE (tracking_code),
    CONSTRAINT ukhrhy2yghr8dampg1jtecuekvp UNIQUE (order_id)
);

-- ---------- shipping_exceptions ----------
CREATE TABLE IF NOT EXISTS shipping_exceptions (
    exception_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    exception_type character varying(100) NOT NULL,
    resolution_note text,
    status character varying(30) NOT NULL,
    shipment_id bigint NOT NULL,
    CONSTRAINT shipping_exceptions_pkey PRIMARY KEY (exception_id)
);

-- ---------- shop_product_configs ----------
CREATE TABLE IF NOT EXISTS shop_product_configs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_available_for_sale boolean NOT NULL,
    local_price numeric(12,2),
    local_promo_price numeric(12,2),
    product_id bigint NOT NULL,
    shop_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT shop_product_configs_pkey PRIMARY KEY (id),
    CONSTRAINT uk_shop_product UNIQUE (shop_id, product_id)
);

-- ---------- shop_work_shifts ----------
CREATE TABLE IF NOT EXISTS shop_work_shifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    note character varying(255),
    shift_date date NOT NULL,
    shift_type character varying(30) NOT NULL,
    shop_id bigint NOT NULL,
    status character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_full_name character varying(255),
    user_id character varying(255) NOT NULL,
    CONSTRAINT shop_work_shifts_pkey PRIMARY KEY (id)
);

-- ---------- staff_audit_log ----------
CREATE TABLE IF NOT EXISTS staff_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    new_value text,
    old_value text,
    actor_id character varying(255) NOT NULL,
    staff_id character varying(255) NOT NULL,
    CONSTRAINT staff_audit_log_pkey PRIMARY KEY (id)
);

-- ---------- staff_performance_evaluations ----------
CREATE TABLE IF NOT EXISTS staff_performance_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    evaluated_by character varying(255) NOT NULL,
    evaluation_period character varying(7) NOT NULL,
    feedback_notes text,
    rating integer NOT NULL,
    sales_target_achievement numeric(5,2),
    shop_id bigint NOT NULL,
    user_full_name character varying(255),
    user_id character varying(255) NOT NULL,
    CONSTRAINT staff_performance_evaluations_pkey PRIMARY KEY (id)
);

-- ---------- stock_reservations ----------
CREATE TABLE IF NOT EXISTS stock_reservations (
    reservation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    reject_reason character varying(500),
    status character varying(30) NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT stock_reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'RELEASED'::character varying])::text[]))),
    CONSTRAINT stock_reservations_pkey PRIMARY KEY (reservation_id)
);

-- ---------- stocktakes ----------
CREATE TABLE IF NOT EXISTS stocktakes (
    stocktake_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actual_quantity integer,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    status character varying(30) NOT NULL,
    warehouse_location character varying(100) NOT NULL,
    CONSTRAINT stocktakes_pkey PRIMARY KEY (stocktake_id)
);

-- ---------- store_featured_categories ----------
CREATE TABLE IF NOT EXISTS store_featured_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    display_order integer NOT NULL,
    shop_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT store_featured_categories_pkey PRIMARY KEY (id),
    CONSTRAINT uk_store_cat UNIQUE (shop_id, category_id)
);

-- ---------- suppliers ----------
CREATE TABLE IF NOT EXISTS suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    email character varying(150),
    name character varying(255) NOT NULL,
    phone character varying(50),
    product_type character varying(150),
    updated_at timestamp(6) without time zone,
    CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);

-- ---------- support_tickets ----------
CREATE TABLE IF NOT EXISTS support_tickets (
    id character varying(255) NOT NULL,
    assigned_to character varying(255),
    channel character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    customer_id character varying(255),
    escalated_to character varying(255),
    order_id bigint,
    priority integer NOT NULL,
    resolved_at timestamp(6) without time zone,
    shop_id bigint,
    status character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    ticket_code character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
    CONSTRAINT ukf48ag9wii7c3owsemq5mqxerk UNIQUE (ticket_code)
);

-- ---------- system_notifications ----------
CREATE TABLE IF NOT EXISTS system_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message text,
    read_at timestamp(6) without time zone,
    severity character varying(20) NOT NULL,
    target_url character varying(255),
    title character varying(255) NOT NULL,
    notification_type character varying(50) NOT NULL,
    CONSTRAINT system_notifications_pkey PRIMARY KEY (id)
);

-- ---------- system_settings ----------
CREATE TABLE IF NOT EXISTS system_settings (
    setting_key character varying(100) NOT NULL,
    description character varying(255),
    updated_at timestamp(6) without time zone,
    setting_value text,
    CONSTRAINT system_settings_pkey PRIMARY KEY (setting_key)
);

-- ---------- ticket_messages ----------
CREATE TABLE IF NOT EXISTS ticket_messages (
    id character varying(255) NOT NULL,
    attachment_url character varying(255),
    created_at timestamp(6) without time zone,
    message text NOT NULL,
    sender_id character varying(255),
    sender_name character varying(255),
    sender_type character varying(255) NOT NULL,
    ticket_id character varying(255) NOT NULL,
    CONSTRAINT ticket_messages_pkey PRIMARY KEY (id)
);

-- ---------- user_behavior_events ----------
CREATE TABLE IF NOT EXISTS user_behavior_events (
    id bigint DEFAULT nextval('user_behavior_events_id_seq'::regclass) NOT NULL,
    user_id character varying(36) NOT NULL,
    product_id bigint NOT NULL,
    event_type character varying(20) NOT NULL,
    session_id character varying(36),
    quantity integer DEFAULT 1,
    price_at_event numeric(15,2),
    source character varying(30),
    device_type character varying(15),
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT user_behavior_events_pkey PRIMARY KEY (id)
);

-- ---------- user_measurements ----------
CREATE TABLE IF NOT EXISTS user_measurements (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    arm_length_cm real,
    chest_cm real,
    created_at timestamp(6) without time zone,
    fit_preference character varying(255),
    height_cm real,
    hip_cm real,
    leg_length_cm real,
    measurement_profile_type character varying(255) NOT NULL,
    note character varying(255),
    preferred_adult_size character varying(255),
    preferred_kids_size character varying(255),
    shoe_size character varying(255),
    shoulder_cm real,
    updated_at timestamp(6) without time zone,
    waist_cm real,
    weight_kg real,
    user_id character varying(255) NOT NULL,
    CONSTRAINT user_measurements_pkey PRIMARY KEY (id),
    CONSTRAINT ukci82fxcvhh6qa4mh98k4xuyaj UNIQUE (user_id)
);

-- ---------- users ----------
CREATE TABLE IF NOT EXISTS users (
    id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    full_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    phone character varying(255),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    avatar_url character varying(255),
    date_of_birth date,
    default_shipping_address character varying(255),
    gender character varying(255),
    role character varying(255) DEFAULT 'USER'::character varying NOT NULL,
    failed_login_attempts integer,
    locked_until timestamp(6) without time zone,
    shop_id bigint,
    employee_code character varying(50),
    lock_reason character varying(500),
    locked_at timestamp(6) without time zone,
    locked_by character varying(255),
    must_change_password boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukob2dx53vn966ek0roock2539f UNIQUE (employee_code)
);

-- ---------- voucher_redemptions ----------
CREATE TABLE IF NOT EXISTS voucher_redemptions (
    id bigint DEFAULT nextval('voucher_redemptions_id_seq'::regclass) NOT NULL,
    voucher_id bigint NOT NULL,
    user_id character varying(255) NOT NULL,
    order_code character varying(255),
    order_total numeric(38,2) DEFAULT 0,
    discount_amount numeric(38,2) DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT voucher_redemptions_pkey PRIMARY KEY (id)
);

-- ---------- vouchers ----------
CREATE TABLE IF NOT EXISTS vouchers (
    id bigint DEFAULT nextval('vouchers_id_seq'::regclass) NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    type character varying(255) DEFAULT 'PERCENT'::character varying NOT NULL,
    discount_value numeric(38,2) NOT NULL,
    min_order_amount numeric(38,2) DEFAULT 0,
    max_discount_amount numeric(38,2),
    max_uses integer,
    used_count integer DEFAULT 0,
    per_user_limit integer DEFAULT 1,
    is_active boolean DEFAULT true,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_by character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    target_group character varying(255) DEFAULT 'ALL'::character varying,
    status character varying(255) DEFAULT 'ACTIVE'::character varying,
    updated_by character varying(255),
    free_shipping boolean DEFAULT false,
    shop_id bigint,
    granted_to_customer_id character varying(255),
    CONSTRAINT vouchers_pkey PRIMARY KEY (id),
    CONSTRAINT vouchers_code_key UNIQUE (code)
);

-- ---------- wishlist_items ----------
CREATE TABLE IF NOT EXISTS wishlist_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    guest_token character varying(255),
    product_id bigint NOT NULL,
    user_id character varying(255),
    CONSTRAINT wishlist_items_pkey PRIMARY KEY (id),
    CONSTRAINT uk6vs8evxuwhdipkio65uu7wv65 UNIQUE (guest_token, product_id),
    CONSTRAINT uktp53unkks741xiqi6m620i7mx UNIQUE (user_id, product_id)
);

-- ============================================================
-- Foreign keys
-- ============================================================
ALTER TABLE campaign_analytics ADD CONSTRAINT campaign_analytics_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE cart_items ADD CONSTRAINT fkn1s4l7h0vm4o259wpu7ft0y2y FOREIGN KEY (product_variant_id) REFERENCES product_variants(id);
ALTER TABLE cart_items ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts(id);
ALTER TABLE carts ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE cod_reconciliation_items ADD CONSTRAINT fkgaqa5v99hb8obxsktljbvy6ps FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id);
ALTER TABLE cod_reconciliation_items ADD CONSTRAINT fksarrw0j0ux168x5scxih4duhi FOREIGN KEY (reconciliation_id) REFERENCES cod_reconciliations(reconciliation_id);
ALTER TABLE inventory_adjustments ADD CONSTRAINT fkwwuks5f08m2blu43u92pc6y0 FOREIGN KEY (inventory_id) REFERENCES inventories(inventory_id);
ALTER TABLE order_items ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE order_items ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE order_notes ADD CONSTRAINT fkgl7kbn92v2whrvmco2ygu3cdt FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE order_status_history ADD CONSTRAINT fknmcbg3mmbt8wfva97ra40nmp3 FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE orders ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE password_reset_tokens ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE product_images ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE product_placements ADD CONSTRAINT fk_placements_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE product_recommendation_tags ADD CONSTRAINT fkdylfh6mrjknnuonqwbg08uhj8 FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE product_reviews ADD CONSTRAINT fk35kxxqe2g9r4mww80w9e3tnw9 FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE product_reviews ADD CONSTRAINT fk58i39bhws2hss3tbcvdmrm60f FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE product_reviews ADD CONSTRAINT fk_product_reviews_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE product_reviews ADD CONSTRAINT fkau5g3dylb9eh7ua5xjjw6uopw FOREIGN KEY (order_item_id) REFERENCES order_items(id);
ALTER TABLE product_style_tags ADD CONSTRAINT fk4beha64dqwamsxbmojy6uj9f5 FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE product_variants ADD CONSTRAINT fkosqitn4s405cynmhb87lkvuau FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE products ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE proof_of_delivery ADD CONSTRAINT fkfe1i4xc3d5anvoa7w8lw05po5 FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id);
ALTER TABLE shipments ADD CONSTRAINT fkrnt4wht95lxxplspltrg9681s FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE shipping_exceptions ADD CONSTRAINT fk511ru8hphbfm46jnkpa3bt4gs FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id);
ALTER TABLE staff_audit_log ADD CONSTRAINT fkflv1p00gv5bxto45hqu3evwtk FOREIGN KEY (actor_id) REFERENCES users(id);
ALTER TABLE staff_audit_log ADD CONSTRAINT fkgw4bveg31rgonu7php0q2vcnr FOREIGN KEY (staff_id) REFERENCES users(id);
ALTER TABLE stock_reservations ADD CONSTRAINT fkp9blb4qtba2t0y1twnfym0tsi FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE store_featured_categories ADD CONSTRAINT fkeiwq2ncsul3yeikfyl4c0u1jc FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE user_measurements ADD CONSTRAINT fkkmrgsg7fmw73wop8m6e6gh5ll FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE voucher_redemptions ADD CONSTRAINT fk_redemptions_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE CASCADE;
ALTER TABLE wishlist_items ADD CONSTRAINT fkmmj2k1i459yu449k3h1vx5abp FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE wishlist_items ADD CONSTRAINT fkqxj7lncd242b59fb78rqegyxj FOREIGN KEY (product_id) REFERENCES products(id);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_banners_active ON public.banners USING btree (is_active, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_analytics_banner ON public.campaign_analytics USING btree (banner_id);
CREATE INDEX IF NOT EXISTS idx_analytics_session ON public.campaign_analytics USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_analytics_user ON public.campaign_analytics USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_voucher ON public.campaign_analytics USING btree (voucher_id);
CREATE INDEX IF NOT EXISTS idx_campaign_analytics_campaign ON public.campaign_analytics USING btree (campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_analytics_event ON public.campaign_analytics USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_placements_key ON public.product_placements USING btree (placement_key, status, "position");
CREATE INDEX IF NOT EXISTS idx_placements_product ON public.product_placements USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_products_prod_type ON public.products USING btree (product_type);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products USING btree (slug);
CREATE INDEX IF NOT EXISTS idx_products_status_isbest ON public.products USING btree (status, is_best_seller);
CREATE INDEX IF NOT EXISTS idx_products_status_isnew ON public.products USING btree (status, is_new);
CREATE INDEX IF NOT EXISTS idx_products_status_price ON public.products USING btree (status, price);
CREATE INDEX IF NOT EXISTS idx_products_status_saleprice ON public.products USING btree (status, sale_price);
CREATE INDEX IF NOT EXISTS idx_products_status_tg ON public.products USING btree (status, target_group);
CREATE INDEX IF NOT EXISTS idx_products_tg_gender ON public.products USING btree (target_group, gender);
CREATE INDEX IF NOT EXISTS idx_ube_created_at ON public.user_behavior_events USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_ube_product_id ON public.user_behavior_events USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_ube_user_id ON public.user_behavior_events USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_redemptions_user_voucher ON public.voucher_redemptions USING btree (user_id, voucher_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_active ON public.vouchers USING btree (is_active, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_vouchers_code ON public.vouchers USING btree (code);
