-- ============================================================
-- V20260929010000__shops_and_soft_delete.sql
--
-- Giai doan 0 cua viec phan quyen du lieu chi nhanh: bang shops that su, khoa
-- ngoai tu cac bang dang mang shop_id ve shops(id), xoa mem + audit cho 5 doi
-- tuong (product, category, manufacturer, supplier, shop_product_config).
--
-- Da kiem tra CHI DOC tren du lieu that truoc khi viet file nay: toan bo
-- shop_id dang ton tai trong moi bang chi nhan 2 gia tri (1 va 2), khong co
-- ban ghi mo coi nao. Xem bao cao khao sat trong lich su trao doi.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Bang shops
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Chi nhanh 1: chi nhanh chinh dang hoat dong. Dia chi de NULL, sua trong
-- trang admin sau (theo yeu cau). Chi nhanh 2: du lieu thu nghiem, danh dau
-- is_active=false nhung KHONG xoa - cac don hang/nhan vien dang tham chieu
-- shop_id=2 van con nguyen, chi khong con hien la chi nhanh dang hoat dong.
INSERT INTO shops (id, name, address, phone, is_active)
VALUES
    (1, 'ET.TEE Chi nhánh 1', NULL, NULL, true),
    (2, 'Chi nhánh 2 (dữ liệu thử nghiệm)', NULL, NULL, false)
ON CONFLICT (id) DO NOTHING;

-- Dong bo sequence sau khi insert id tuong minh, tranh trung id o lan tao moi.
SELECT setval(pg_get_serial_sequence('shops', 'id'), GREATEST((SELECT MAX(id) FROM shops), 1));


-- ------------------------------------------------------------
-- 2. Khoa ngoai tu cac bang mang shop_id ve shops(id)
-- ------------------------------------------------------------
-- Da kiem tra CHI DOC: moi bang duoi day chi co gia tri shop_id trong {1, 2}
-- hoac NULL, nen an toan them FK ngay. NULL van hop le (vd: users khong thuoc
-- chi nhanh nao nhu ADMIN/khach hang) - khong dat NOT NULL o day.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_shop') THEN
        ALTER TABLE users ADD CONSTRAINT fk_users_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_shop') THEN
        ALTER TABLE orders ADD CONSTRAINT fk_orders_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventories_shop') THEN
        ALTER TABLE inventories ADD CONSTRAINT fk_inventories_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_vouchers_shop') THEN
        ALTER TABLE vouchers ADD CONSTRAINT fk_vouchers_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_support_tickets_shop') THEN
        ALTER TABLE support_tickets ADD CONSTRAINT fk_support_tickets_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shop_work_shifts_shop') THEN
        ALTER TABLE shop_work_shifts ADD CONSTRAINT fk_shop_work_shifts_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cskh_voucher_quotas_shop') THEN
        ALTER TABLE cskh_voucher_quotas ADD CONSTRAINT fk_cskh_voucher_quotas_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cskh_voucher_grants_shop') THEN
        ALTER TABLE cskh_voucher_grants ADD CONSTRAINT fk_cskh_voucher_grants_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shop_product_configs_shop') THEN
        ALTER TABLE shop_product_configs ADD CONSTRAINT fk_shop_product_configs_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_staff_performance_evaluations_shop') THEN
        ALTER TABLE staff_performance_evaluations ADD CONSTRAINT fk_staff_performance_evaluations_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_featured_categories_shop') THEN
        ALTER TABLE store_featured_categories ADD CONSTRAINT fk_store_featured_categories_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
    -- suppliers.shop_id duoc them o phan 4 ben duoi, FK khai bao cung mot cho o do.
END $$;


-- ------------------------------------------------------------
-- 3a. Xoa mem + audit cho categories
-- ------------------------------------------------------------
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

UPDATE categories SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP) WHERE created_at IS NULL;

-- Cac rang buoc unique cu tren categories chong cheo nhau (mot vai constraint
-- la du thua tu cac lan Hibernate ddl-auto=update khac nhau; xem doi chieu
-- trong bao cao khao sat). Bo het, thay bang 2 UNIQUE INDEX PARTIAL chi tinh
-- ban ghi con song, de mot ten/slug da bi xoa co the dung lai duoc.
ALTER TABLE categories DROP CONSTRAINT IF EXISTS uk_cat_name_parent;
ALTER TABLE categories DROP CONSTRAINT IF EXISTS uk_cat_slug;
ALTER TABLE categories DROP CONSTRAINT IF EXISTS ukoul14ho7bctbefv8jywp5v3i2; -- trung voi uk_cat_slug
ALTER TABLE categories DROP CONSTRAINT IF EXISTS ukt8o6pivur7nn124jehx7cygw5; -- UNIQUE(name) don le, sai pham vi so voi (name, parent_id) hien tai

CREATE UNIQUE INDEX IF NOT EXISTS uk_cat_slug_active ON categories(slug) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_cat_name_parent_active ON categories(name, parent_id) WHERE deleted_at IS NULL;


-- ------------------------------------------------------------
-- 3b. Xoa mem + audit cho manufacturers
-- ------------------------------------------------------------
ALTER TABLE manufacturers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE manufacturers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE manufacturers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
-- Khong co rang buoc unique nao tren manufacturers (da kiem tra CHI DOC), nen
-- khong can index partial rieng.


-- ------------------------------------------------------------
-- 4. Suppliers: them shop_id (NULL = dung chung) + xoa mem + audit
-- ------------------------------------------------------------
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

-- 4 nha cung ung dang co (vai Bao Minh, khoa keo YKK, phu lieu Song Toan, bao
-- bi BoxEco) la du lieu cap thuong hieu tu truoc, giu shop_id = NULL = dung
-- chung toan chuoi thay vi gan cho mot chi nhanh cu the.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_suppliers_shop') THEN
        ALTER TABLE suppliers ADD CONSTRAINT fk_suppliers_shop FOREIGN KEY (shop_id) REFERENCES shops(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_suppliers_shop_id ON suppliers(shop_id);


-- ------------------------------------------------------------
-- 5. Xoa mem + audit cho shop_product_configs
-- ------------------------------------------------------------
ALTER TABLE shop_product_configs ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE shop_product_configs ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE shop_product_configs ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE shop_product_configs DROP CONSTRAINT IF EXISTS uk_shop_product;
CREATE UNIQUE INDEX IF NOT EXISTS uk_shop_product_active
    ON shop_product_configs(shop_id, product_id) WHERE deleted_at IS NULL;


-- ------------------------------------------------------------
-- 6. Audit cho products (xoa mem tai su dung cot status co san, xem Product.java)
-- ------------------------------------------------------------
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- Rang buoc unique(slug) cu chan viec dung lai slug cua mot san pham da bi
-- "xoa" (status='DELETED'). Thay bang UNIQUE INDEX PARTIAL loai tru DELETED.
ALTER TABLE products DROP CONSTRAINT IF EXISTS ukostq1ec3toafnjok09y9l7dox;
CREATE UNIQUE INDEX IF NOT EXISTS uk_products_slug_active
    ON products(slug) WHERE status <> 'DELETED';
