-- ============================================================
-- V20260930000000__stocktake_shop_id_and_marketing_tables.sql
--
-- Phase 2 / Phase 3 database consistency:
--   1. Add shop_id to stocktakes, backfill existing records with shop_id = 1, add index
--   2. Create shops table and seed primary branches
--   3. Create marketing_posts table for Marketing Staff posts management
--   4. Add type, target_audience, and shop_id columns to campaigns
-- ============================================================

-- 1. stocktakes.shop_id
ALTER TABLE stocktakes ADD COLUMN IF NOT EXISTS shop_id BIGINT;
UPDATE stocktakes SET shop_id = 1 WHERE shop_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_stocktakes_shop_id ON stocktakes(shop_id);

-- 2. shops table
CREATE TABLE IF NOT EXISTS shops (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    address character varying(500),
    phone character varying(50),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT shops_pkey PRIMARY KEY (id)
);

INSERT INTO shops (id, name, address, phone, is_active, created_at, updated_at) VALUES
(1, 'ET.TEE Flagship Store', '123 Nguyen Trai, Q.1, TP.HCM', '0901234567', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ET.TEE Hanoi Branch', '456 Cau Giay, Ha Noi', '0907654321', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- 3. marketing_posts table
CREATE TABLE IF NOT EXISTS marketing_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    excerpt character varying(500),
    content text,
    cover_image_url character varying(500),
    status character varying(30) DEFAULT 'DRAFT' NOT NULL,
    author character varying(100),
    published_at timestamp(6) without time zone,
    views integer DEFAULT 0 NOT NULL,
    tags character varying(500),
    shop_id bigint,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT marketing_posts_pkey PRIMARY KEY (id),
    CONSTRAINT uk_marketing_posts_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_marketing_posts_status ON marketing_posts(status);
CREATE INDEX IF NOT EXISTS idx_marketing_posts_slug ON marketing_posts(slug);

-- 4. campaigns table enhancements
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS type character varying(50) DEFAULT 'SEASONAL';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS target_audience character varying(50) DEFAULT 'ALL';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS shop_id bigint;
CREATE INDEX IF NOT EXISTS idx_campaigns_shop_id ON campaigns(shop_id);
