-- Phieu nhap kho (lich su) va de xuat nhap hang cua nhan vien kho.
-- Truoc day POST /inbound chi cong ton ma khong luu lai phieu, va nut "De xuat nhap"
-- goi mot endpoint khong ton tai.
CREATE TABLE IF NOT EXISTS goods_receipts (
    receipt_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_name character varying(200) NOT NULL,
    quantity integer NOT NULL,
    warehouse_location character varying(100),
    supplier character varying(200),
    note character varying(500),
    shop_id bigint,
    created_by character varying(255),
    status character varying(30) DEFAULT 'RECEIVED' NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT goods_receipts_pkey PRIMARY KEY (receipt_id),
    CONSTRAINT goods_receipts_qty_positive CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS idx_goods_receipts_shop_created ON goods_receipts (shop_id, created_at DESC);

CREATE TABLE IF NOT EXISTS restock_requests (
    request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_name character varying(200) NOT NULL,
    quantity integer NOT NULL,
    note character varying(500),
    shop_id bigint,
    requested_by character varying(255),
    status character varying(30) DEFAULT 'PENDING' NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT restock_requests_pkey PRIMARY KEY (request_id),
    CONSTRAINT restock_requests_qty_positive CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS idx_restock_requests_shop_created ON restock_requests (shop_id, created_at DESC);
